# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='module_num',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
