# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_module_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetextmodule',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='freetextmodule',
            name='position',
            field=models.IntegerField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='freetextmodule',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='freetextmodule',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='generalinfomodule',
            name='identity',
            field=models.CharField(blank=True, choices=[('01_autistic', 'I am autistic'), ('02_have_aut', 'I have autism'), ('03_spectrum', 'I am on the autism spectrum'), ('04_asd', 'I have an autism spectrum disorder'), ('05_neurodiv', 'I am neurodivergent'), ('06_asp_syn', 'I have aspergers syndrome'), ('07_aspie', 'I am an aspie')], default='', max_length=32, verbose_name='Identity'),
        ),
        migrations.AlterField(
            model_name='generalinfomodule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='generalinfomodule',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='generalinfomodule',
            name='position',
            field=models.IntegerField(verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Page Title'),
        ),
    ]
