# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 09:57
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20171103_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeListModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='Items')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreePictureModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModulePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.FreePictureModule', verbose_name='module')),
            ],
        ),
    ]
