# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 09:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_freelistmodule_freepicturemodule_modulepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMethodsModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('situation', models.CharField(blank=True, default='', max_length=255, verbose_name='Situation')),
                ('you_to_me_choices', pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_spoken', 'Spoken language'), ('02_written', 'Written language'), ('03_text_aac', 'Text based alternative to speech'), ('04_pic_aac', 'Picture based alternative to speech'), ('05_off_sign', 'Official signlanguage'), ('06_other_sign', 'Other signs, gestures or behaviours')], max_length=32), blank=True, size=None, verbose_name='You can use')),
                ('you_to_me_free', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='Other communication methods you can use')),
                ('me_to_you_choices', pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_spoken', 'Spoken language'), ('02_written', 'Written language'), ('03_text_aac', 'Text based alternative to speech'), ('04_pic_aac', 'Picture based alternative to speech'), ('05_off_sign', 'Official signlanguage'), ('06_other_sign', 'Other signs, gestures or behaviours')], max_length=32), blank=True, size=None, verbose_name='I will use')),
                ('me_to_you_free', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='Other communication methods I might use')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
