# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 12:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20171206_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoDontModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('do_choices', pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_do_time', 'Leave me enough time to answer your questions or to make decisions'), ('02_do_light', 'Use natural light and turn off fluorescent lights if possible'), ('03_do_quiet', 'Try to find a quiet room or space for me'), ('04_do_headphones', 'Let me use my headphones to listen to my favorite music'), ('05_do_ear_protect', 'Let me use my ear protection to block out noises'), ('06_do_fidget', 'Let me fidget, move around, flap my arms or make other sounds or motions'), ('07_do_calm', 'Talk to me with a calm voice'), ('08_do_changes', 'Tel me about changes in plans as soon as possible'), ('09_do_noises', 'Turn of the TV, radio or other things that make noise'), ('10_do_instructions', 'Give me clear instructions if I have to do something'), ('11_do_prepare', 'Tell me what is going to happen beforehand')], max_length=32), blank=True, size=None, verbose_name='Things others can do to help you')),
                ('do_free', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='More things others can do')),
                ('ask_choices', pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_ask_touch', 'Ask before you touch me'), ('02_ask_stuff', 'Ask befor touching my stuff'), ('03_ask_ready', 'Ask me if I am ready to go (and where we go to) befor you take me to a new place'), ('04_ask_communicate', 'Ask me about what method of communication I want to use'), ('05_ask_talk', 'Ask me if I want to talk or socialize before introducing me to new people')], max_length=32), blank=True, size=None, verbose_name='Things people should ask you about')),
                ('ask_free', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='More things others should ask')),
                ('dont_choices', pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_dont_touch', "Don't touch me without permission"), ('02_dont_eye', "Don't force me to make eye contact"), ('03_dont_questions', "Don't ask me to many questions"), ('04_dont_close', 'Do not sit or stand close to me unless it is necessary'), ('05_chitchat', 'Avoid chitchat'), ('06_dont_talk', "Don't talk a lot to try to calm me, as this has the contrary effect"), ('07_dont_noises', "Don't make unexpected hard noises such as slamming a door")], max_length=32), blank=True, size=None, verbose_name='Things others should not do')),
                ('dont_free', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name="More things others shouldn't do")),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
