# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_dodontmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, default='', max_length=255, verbose_name='Intake time')),
                ('quantity', models.CharField(blank=True, default='', max_length=255, verbose_name='Intake quantity')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Medication name')),
                ('remarks', models.TextField(blank=True, default='', verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medicationitem',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.MedicationModule', verbose_name='module'),
        ),
        migrations.AddField(
            model_name='medicationintake',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.MedicationItem', verbose_name='medication'),
        ),
    ]
