# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 14:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contactmodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensoryModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('sound', models.CharField(choices=[('00_sens_none', 'Do not include'), ('01_sens_v_low', 'Very low'), ('02_sens_low', 'Lower than average'), ('03_sens_med', 'Average'), ('04_sens_high', 'Higher than average'), ('05_sens_v_high', 'Very high')], default='00_sens_none', max_length=32, verbose_name='Sensitivity to sound')),
                ('light', models.CharField(choices=[('00_sens_none', 'Do not include'), ('01_sens_v_low', 'Very low'), ('02_sens_low', 'Lower than average'), ('03_sens_med', 'Average'), ('04_sens_high', 'Higher than average'), ('05_sens_v_high', 'Very high')], default='00_sens_none', max_length=32, verbose_name='Sensitivity to light')),
                ('smell', models.CharField(choices=[('00_sens_none', 'Do not include'), ('01_sens_v_low', 'Very low'), ('02_sens_low', 'Lower than average'), ('03_sens_med', 'Average'), ('04_sens_high', 'Higher than average'), ('05_sens_v_high', 'Very high')], default='00_sens_none', max_length=32, verbose_name='Sensitivity to smells')),
                ('temperature', models.CharField(choices=[('00_sens_none', 'Do not include'), ('01_sens_v_low', 'Very low'), ('02_sens_low', 'Lower than average'), ('03_sens_med', 'Average'), ('04_sens_high', 'Higher than average'), ('05_sens_v_high', 'Very high')], default='00_sens_none', max_length=32, verbose_name='Sensitivity to temperature')),
                ('extra_choices', pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_extra_fluo', "I can't cope with fluorescent lighting"), ('02_extra_multi', 'I have trouble processing more than on sense at a time, for example hearing you while looking at something'), ('03_extra_pain', 'I have difficulties recognizing and or reporting pain or other symptoms')], max_length=32), blank=True, size=None, verbose_name='Additional sensory info')),
                ('extra_free', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='More additional sensory info')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
