# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 11:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20171213_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(blank=True, default='', max_length=255, verbose_name='Situation')),
                ('you_to_me_choices', pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_spoken', 'Spoken language'), ('02_written', 'Written language'), ('03_text_aac', 'Text based alternative to speech'), ('04_pic_aac', 'Picture based alternative to speech'), ('05_off_sign', 'Official signlanguage'), ('06_other_sign', 'Other signs, gestures or behaviours')], max_length=32), blank=True, size=None, verbose_name='You can use')),
                ('you_to_me_free', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='Other communication methods you can use')),
                ('me_to_you_choices', pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_spoken', 'Spoken language'), ('02_written', 'Written language'), ('03_text_aac', 'Text based alternative to speech'), ('04_pic_aac', 'Picture based alternative to speech'), ('05_off_sign', 'Official signlanguage'), ('06_other_sign', 'Other signs, gestures or behaviours')], max_length=32), blank=True, size=None, verbose_name='I will use')),
                ('me_to_you_free', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='Other communication methods I might use')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Position')),
                ('suggestions_choices', pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_simple', 'Use simple words and short senteces.'), ('02_concrete', 'Be very concrete and specific. Avoid very broad questions.'), ('03_pictures', 'Show me diagrams or pictures whenever possible.'), ('04_write', 'Write down important information or instructions for me.'), ('05_detailed', 'Give me very detailed information.'), ('06_important', 'Focus only on the most important information.'), ('07_questions', 'Be patient with me if I need to ask a lot of questions.'), ('08_processing', 'Give me extra time to process what you have said. Especially if I have to answer questions.'), ('09_noises', 'Do not try to talk to me while ther are other noises.'), ('10_not_rude', "If I seem rude, I don't mean it. I'm just really direct."), ('11_literally', 'I often take language too literally.'), ('12_body_language', 'I may have difficulty understanding tone of voice, facial expressions, or body language.'), ('13_hard_fluent', 'I may have a hard time communicating, even if my speech sounds fluent.'), ('14_involved', 'I can be involved in decisions even though I have difficulty speaking.'), ('15_situation', 'My ability to communicate changes a lot, depending on the situation.'), ('16_telephone', 'I have a hard time using the telephone.')], max_length=32), blank=True, size=None, verbose_name='Communication suggestions')),
                ('suggestions_free', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='Other communication suggestions')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='communicationmethodsmodule',
            name='page',
        ),
        migrations.DeleteModel(
            name='CommunicationMethodsModule',
        ),
        migrations.AddField(
            model_name='communicationmethods',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.CommunicationModule', verbose_name='module'),
        ),
    ]
