# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20171218_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationintake',
            name='position',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='medicationitem',
            name='position',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
    ]
