# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20171221_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communicationmodule',
            options={'verbose_name': 'Communication module'},
        ),
        migrations.AlterModelOptions(
            name='contactmodule',
            options={'verbose_name': 'Contact module'},
        ),
        migrations.AlterModelOptions(
            name='dodontmodule',
            options={'verbose_name': "Do's and Don'ts module"},
        ),
        migrations.AlterModelOptions(
            name='freelistmodule',
            options={'verbose_name': 'Free list module'},
        ),
        migrations.AlterModelOptions(
            name='freepicturemodule',
            options={'verbose_name': 'Free picture module'},
        ),
        migrations.AlterModelOptions(
            name='freetextmodule',
            options={'verbose_name': 'Free text module'},
        ),
        migrations.AlterModelOptions(
            name='generalinfomodule',
            options={'verbose_name': 'General info module'},
        ),
        migrations.AlterModelOptions(
            name='medicationintake',
            options={'ordering': ['medication', 'position']},
        ),
        migrations.AlterModelOptions(
            name='medicationitem',
            options={'ordering': ['module', 'position']},
        ),
        migrations.AlterModelOptions(
            name='medicationmodule',
            options={'verbose_name': 'Medication module'},
        ),
        migrations.AlterModelOptions(
            name='sensorymodule',
            options={'verbose_name': 'Sensory module'},
        ),
    ]
