# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 19:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import pages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20180109_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationmethods',
            name='me_to_you_choices',
            field=pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_spoken', 'Spoken language'), ('02_written', 'Written language'), ('03_text_aac', 'Text based alternative to speech'), ('04_pic_aac', 'Picture based alternative to speech'), ('05_off_sign', 'Official sign-language'), ('06_other_sign', 'Other signs, gestures or behaviours')], max_length=32), blank=True, default=list, size=None, verbose_name='I will use'),
        ),
        migrations.AlterField(
            model_name='communicationmethods',
            name='me_to_you_free',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Other communication methods I might use'),
        ),
        migrations.AlterField(
            model_name='communicationmethods',
            name='you_to_me_choices',
            field=pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_spoken', 'Spoken language'), ('02_written', 'Written language'), ('03_text_aac', 'Text based alternative to speech'), ('04_pic_aac', 'Picture based alternative to speech'), ('05_off_sign', 'Official sign-language'), ('06_other_sign', 'Other signs, gestures or behaviours')], max_length=32), blank=True, default=list, size=None, verbose_name='You can use'),
        ),
        migrations.AlterField(
            model_name='communicationmethods',
            name='you_to_me_free',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Other communication methods you can use'),
        ),
        migrations.AlterField(
            model_name='communicationmodule',
            name='suggestions_choices',
            field=pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_simple', 'Use simple words and short sentences.'), ('02_concrete', 'Be very concrete and specific. Avoid very broad questions.'), ('03_pictures', 'Show me diagrams or pictures whenever possible.'), ('04_write', 'Write down important information or instructions for me.'), ('05_detailed', 'Give me very detailed information.'), ('06_important', 'Focus only on the most important information.'), ('07_questions', 'Be patient with me if I need to ask a lot of questions.'), ('08_processing', 'Give me extra time to process what you have said. Especially if I have to answer questions.'), ('09_noises', 'Do not try to talk to me while there are other noises.'), ('10_not_rude', "If I seem rude, I don't mean it. I'm just really direct."), ('11_literally', 'I often take language too literally.'), ('12_body_language', 'I may have difficulty understanding tone of voice, facial expressions, or body language.'), ('13_hard_fluent', 'I may have a hard time communicating, even if my speech sounds fluent.'), ('14_involved', 'I can be involved in decisions even though I have difficulty speaking.'), ('15_situation', 'My ability to communicate changes a lot, depending on the situation.'), ('16_telephone', 'I have a hard time using the telephone.')], max_length=32), blank=True, default=list, size=None, verbose_name='Communication suggestions'),
        ),
        migrations.AlterField(
            model_name='communicationmodule',
            name='suggestions_free',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Other communication suggestions'),
        ),
        migrations.AlterField(
            model_name='dodontmodule',
            name='ask_choices',
            field=pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_ask_touch', 'Ask before you touch me'), ('02_ask_stuff', 'Ask before touching my stuff'), ('03_ask_ready', 'Ask me if I am ready to go (and where we go to) before you take me to a new place'), ('04_ask_communicate', 'Ask me about what method of communication I want to use'), ('05_ask_talk', 'Ask me if I want to talk or socialize before introducing me to new people')], max_length=32), blank=True, default=list, size=None, verbose_name='Things people should ask you about'),
        ),
        migrations.AlterField(
            model_name='dodontmodule',
            name='ask_free',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='More things others should ask'),
        ),
        migrations.AlterField(
            model_name='dodontmodule',
            name='do_choices',
            field=pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_do_time', 'Leave me enough time to answer your questions or to make decisions'), ('02_do_light', 'Use natural light and turn off fluorescent lights if possible'), ('03_do_quiet', 'Try to find a quiet room or space for me'), ('04_do_headphones', 'Let me use my headphones to listen to my favorite music'), ('05_do_ear_protect', 'Let me use my ear protection to block out noises'), ('06_do_fidget', 'Let me fidget, move around, flap my arms or make other sounds or motions'), ('07_do_calm', 'Talk to me with a calm voice'), ('08_do_changes', 'Tel me about changes in plans as soon as possible'), ('09_do_noises', 'Turn of the TV, radio or other things that make noise'), ('10_do_instructions', 'Give me clear instructions if I have to do something'), ('11_do_prepare', 'Tell me what is going to happen beforehand')], max_length=32), blank=True, default=list, size=None, verbose_name='Things others can do to help you'),
        ),
        migrations.AlterField(
            model_name='dodontmodule',
            name='do_free',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='More things others can do'),
        ),
        migrations.AlterField(
            model_name='dodontmodule',
            name='dont_choices',
            field=pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_dont_touch', "Don't touch me without permission"), ('02_dont_eye', "Don't force me to make eye contact"), ('03_dont_questions', "Don't ask me too many questions"), ('04_dont_close', 'Do not sit or stand close to me unless it is necessary'), ('05_chitchat', 'Avoid chitchat'), ('06_dont_talk', "Don't talk a lot to try to calm me, as this has the contrary effect"), ('07_dont_noises', "Don't make unexpected hard noises such as slamming a door")], max_length=32), blank=True, default=list, size=None, verbose_name='Things others should not do'),
        ),
        migrations.AlterField(
            model_name='dodontmodule',
            name='dont_free',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name="More things others shouldn't do"),
        ),
        migrations.AlterField(
            model_name='freelistmodule',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='generalinfomodule',
            name='identity',
            field=models.CharField(blank=True, choices=[('01_autistic', 'I am autistic'), ('02_have_aut', 'I have autism'), ('03_spectrum', 'I am on the autism spectrum'), ('04_asd', 'I have an autism spectrum disorder'), ('05_neurodiv', 'I am neurodivergent'), ('06_asp_syn', 'I have Asperger syndrome'), ('07_aspie', 'I am an aspie')], default='', max_length=32, verbose_name='Identity'),
        ),
        migrations.AlterField(
            model_name='sensorymodule',
            name='extra_choices',
            field=pages.fields.ChoiceArrayField(base_field=models.CharField(choices=[('01_extra_fluo', "I can't cope with fluorescent lighting"), ('02_extra_multi', 'I have trouble processing more than on sense at a time, for example hearing you while looking at something'), ('03_extra_pain', 'I have difficulties recognizing and or reporting pain or other symptoms')], max_length=32), blank=True, default=list, size=None, verbose_name='Additional sensory info'),
        ),
        migrations.AlterField(
            model_name='sensorymodule',
            name='extra_free',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='More additional sensory info'),
        ),
    ]
