# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-30 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_page_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='page',
            name='token',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='page',
            name='token_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Token Count'),
        ),
        migrations.AddField(
            model_name='page',
            name='token_ts',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token created at'),
        ),
    ]
