# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20180211_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinfomodule',
            name='identity_free',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Specify your identity if you chose other above'),
        ),
        migrations.AddField(
            model_name='generalinfomodule',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='infomodule', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='generalinfomodule',
            name='pronouns',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Prefered pronouns'),
        ),
        migrations.AddField(
            model_name='generalinfomodule',
            name='remarks',
            field=models.TextField(blank=True, default='', verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='generalinfomodule',
            name='identity',
            field=models.CharField(blank=True, choices=[('01_autistic', 'I am autistic'), ('02_have_aut', 'I have autism'), ('03_spectrum', 'I am on the autism spectrum'), ('04_asd', 'I have an autism spectrum disorder'), ('05_neurodiv', 'I am neurodivergent'), ('06_asp_syn', 'I have Asperger syndrome'), ('07_aspie', 'I am an aspie'), ('08_other', 'Other')], default='', max_length=32, verbose_name='Identity'),
        ),
        migrations.AlterField(
            model_name='modulepicture',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Image description'),
        ),
        migrations.AlterField(
            model_name='modulepicture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picturemodule', verbose_name='Image'),
        ),
    ]
