# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_auto_20180307_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_example',
            field=models.BooleanField(default=False, verbose_name='Is example'),
        ),
    ]
