# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-21 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_data_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfomodule',
            name='pronouns',
            field=models.CharField(blank=True, default='', help_text='She/Her/Hers, He/Him/His, They/Them/Theirs, etc.', max_length=255, verbose_name='Prefered pronouns'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='', help_text='No inspiration? You can leave this field empty or fill it out later', max_length=255, verbose_name='Page Title'),
        ),
    ]
