# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20180321_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationmodule',
            name='position',
            field=models.IntegerField(help_text='1-based', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='contactmodule',
            name='position',
            field=models.IntegerField(help_text='1-based', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='dodontmodule',
            name='position',
            field=models.IntegerField(help_text='1-based', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='freelistmodule',
            name='position',
            field=models.IntegerField(help_text='1-based', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='freepicturemodule',
            name='position',
            field=models.IntegerField(help_text='1-based', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='freetextmodule',
            name='position',
            field=models.IntegerField(help_text='1-based', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='generalinfomodule',
            name='position',
            field=models.IntegerField(help_text='1-based', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='medicationmodule',
            name='position',
            field=models.IntegerField(help_text='1-based', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, help_text='consider non active views as deleted', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='page',
            name='is_visible',
            field=models.BooleanField(default=False, help_text='visible to other users than the creating user.', verbose_name='Is visible'),
        ),
        migrations.AlterField(
            model_name='sensorymodule',
            name='position',
            field=models.IntegerField(help_text='1-based', verbose_name='Position'),
        ),
    ]
